#include <sol.hpp>
#include <BWAPI.h>
#include "BWAPI_Lua.h"

using namespace BWAPI;

namespace BWAPI_Lua
{
	void bindUnitType(sol::table module)
	{
		auto unitType = module.create_simple_usertype<UnitType>(
			"whatBuilds", [](const UnitType& unitType) {
				auto pair = unitType.whatBuilds();
				return std::make_tuple(pair.first, pair.second);
			},
			"requiredUnits", [](const UnitType& unitType, sol::this_state s) {
				sol::state_view lua(s);
				auto tbl = lua.create_table();
				auto requiredUnits = unitType.requiredUnits();
				for (auto const& requiredUnit : requiredUnits)
				{
					tbl[requiredUnit.first.getID()] = requiredUnit.second;
				}
				return tbl;
			}
		);
		bindType<UnitType>(unitType);
		unitType.set("isWorker", &UnitType::isWorker);
		unitType.set("isResourceDepot", &UnitType::isResourceDepot);
		unitType.set("getRace", &UnitType::getRace);
		unitType.set("tileSize", &UnitType::tileSize);
		unitType.set("isBuilding", &UnitType::isBuilding);
		unitType.set("buildTime", &UnitType::buildTime);
		unitType.set("requiredTech", &UnitType::requiredTech);
		unitType.set("cloakingTech", &UnitType::cloakingTech);
		unitType.set("abilities", &UnitType::abilities);
		unitType.set("upgrades", &UnitType::upgrades);
		unitType.set("armorUpgrade", &UnitType::armorUpgrade);
		unitType.set("maxHitPoints", &UnitType::maxHitPoints);
		unitType.set("maxShields", &UnitType::maxShields);
		unitType.set("maxEnergy", &UnitType::maxEnergy);
		unitType.set("armor", &UnitType::armor);
		unitType.set("mineralPrice", &UnitType::mineralPrice);
		unitType.set("gasPrice", &UnitType::gasPrice);
		unitType.set("buildTime", &UnitType::buildTime);
		unitType.set("supplyRequired", &UnitType::supplyRequired);
		unitType.set("supplyProvided", &UnitType::supplyProvided);
		unitType.set("spaceRequired", &UnitType::spaceRequired);
		unitType.set("spaceProvided", &UnitType::spaceProvided);
		unitType.set("buildScore", &UnitType::buildScore);
		unitType.set("destroyScore", &UnitType::destroyScore);
		unitType.set("size", &UnitType::size);
		unitType.set("tileWidth", &UnitType::tileWidth);
		unitType.set("tileHeight", &UnitType::tileHeight);
		unitType.set("tileSize", &UnitType::tileSize);
		unitType.set("dimensionLeft", &UnitType::dimensionLeft);
		unitType.set("dimensionUp", &UnitType::dimensionUp);
		unitType.set("dimensionRight", &UnitType::dimensionRight);
		unitType.set("dimensionDown", &UnitType::dimensionDown);
		unitType.set("width", &UnitType::width);
		unitType.set("height", &UnitType::height);
		unitType.set("seekRange", &UnitType::seekRange);
		unitType.set("sightRange", &UnitType::sightRange);
		unitType.set("groundWeapon", &UnitType::groundWeapon);
		unitType.set("maxGroundHits", &UnitType::maxGroundHits);
		unitType.set("airWeapon", &UnitType::airWeapon);
		unitType.set("maxAirHits", &UnitType::maxAirHits);
		unitType.set("topSpeed", &UnitType::topSpeed);
		unitType.set("acceleration", &UnitType::acceleration);
		unitType.set("haltDistance", &UnitType::haltDistance);
		unitType.set("turnRadius", &UnitType::turnRadius);
		unitType.set("canProduce", &UnitType::canProduce);
		unitType.set("canAttack", &UnitType::canAttack);
		unitType.set("canMove", &UnitType::canMove);
		unitType.set("isFlyer", &UnitType::isFlyer);
		unitType.set("regeneratesHP", &UnitType::regeneratesHP);
		unitType.set("isSpellcaster", &UnitType::isSpellcaster);
		unitType.set("hasPermanentCloak", &UnitType::hasPermanentCloak);
		unitType.set("isInvincible", &UnitType::isInvincible);
		unitType.set("isOrganic", &UnitType::isOrganic);
		unitType.set("isMechanical", &UnitType::isMechanical);
		unitType.set("isRobotic", &UnitType::isRobotic);
		unitType.set("isDetector", &UnitType::isDetector);
		unitType.set("isResourceContainer", &UnitType::isResourceContainer);
		unitType.set("isResourceDepot", &UnitType::isResourceDepot);
		unitType.set("isRefinery", &UnitType::isRefinery);
		unitType.set("isWorker", &UnitType::isWorker);
		unitType.set("requiresPsi", &UnitType::requiresPsi);
		unitType.set("requiresCreep", &UnitType::requiresCreep);
		unitType.set("isTwoUnitsInOneEgg", &UnitType::isTwoUnitsInOneEgg);
		unitType.set("isBurrowable", &UnitType::isBurrowable);
		unitType.set("isCloakable", &UnitType::isCloakable);
		unitType.set("isBuilding", &UnitType::isBuilding);
		unitType.set("isAddon", &UnitType::isAddon);
		unitType.set("isFlyingBuilding", &UnitType::isFlyingBuilding);
		unitType.set("isNeutral", &UnitType::isNeutral);
		unitType.set("isHero", &UnitType::isHero);
		unitType.set("isPowerup", &UnitType::isPowerup);
		unitType.set("isBeacon", &UnitType::isBeacon);
		unitType.set("isFlagBeacon", &UnitType::isFlagBeacon);
		unitType.set("isSpecialBuilding", &UnitType::isSpecialBuilding);
		unitType.set("isSpell", &UnitType::isSpell);
		unitType.set("producesCreep", &UnitType::producesCreep);
		unitType.set("producesLarva", &UnitType::producesLarva);
		unitType.set("isMineralField", &UnitType::isMineralField);
		unitType.set("isCritter", &UnitType::isCritter);
		unitType.set("canBuildAddon", &UnitType::canBuildAddon);
		unitType.set("buildsWhat", &UnitType::buildsWhat);
		unitType.set("researchesWhat", &UnitType::researchesWhat);
		unitType.set("upgradesWhat", &UnitType::upgradesWhat);
		module.set_usertype("UnitType", unitType);

		auto unitTypeSet = module.create_simple_usertype<UnitType::set>();
		bindSetContainer<UnitType::set, UnitType>(unitTypeSet);
		module.set_usertype("UnitTypeset", unitTypeSet);

		auto unitTypes = module.create_named("UnitTypes");
		unitTypes["Terran_Firebat"] = &UnitTypes::Terran_Firebat;
		unitTypes["Terran_Ghost"] = &UnitTypes::Terran_Ghost;
		unitTypes["Terran_Goliath"] = &UnitTypes::Terran_Goliath;
		unitTypes["Terran_Marine"] = &UnitTypes::Terran_Marine;
		unitTypes["Terran_Medic"] = &UnitTypes::Terran_Medic;
		unitTypes["Terran_SCV"] = &UnitTypes::Terran_SCV;
		unitTypes["Terran_Siege_Tank_Siege_Mode"] = &UnitTypes::Terran_Siege_Tank_Siege_Mode;
		unitTypes["Terran_Siege_Tank_Tank_Mode"] = &UnitTypes::Terran_Siege_Tank_Tank_Mode;
		unitTypes["Terran_Vulture"] = &UnitTypes::Terran_Vulture;
		unitTypes["Terran_Vulture_Spider_Mine"] = &UnitTypes::Terran_Vulture_Spider_Mine;
		unitTypes["Terran_Battlecruiser"] = &UnitTypes::Terran_Battlecruiser;
		unitTypes["Terran_Dropship"] = &UnitTypes::Terran_Dropship;
		unitTypes["Terran_Nuclear_Missile"] = &UnitTypes::Terran_Nuclear_Missile;
		unitTypes["Terran_Science_Vessel"] = &UnitTypes::Terran_Science_Vessel;
		unitTypes["Terran_Valkyrie"] = &UnitTypes::Terran_Valkyrie;
		unitTypes["Terran_Wraith"] = &UnitTypes::Terran_Wraith;
		unitTypes["Hero_Alan_Schezar"] = &UnitTypes::Hero_Alan_Schezar;
		unitTypes["Hero_Alexei_Stukov"] = &UnitTypes::Hero_Alexei_Stukov;
		unitTypes["Hero_Arcturus_Mengsk"] = &UnitTypes::Hero_Arcturus_Mengsk;
		unitTypes["Hero_Edmund_Duke_Tank_Mode"] = &UnitTypes::Hero_Edmund_Duke_Tank_Mode;
		unitTypes["Hero_Edmund_Duke_Siege_Mode"] = &UnitTypes::Hero_Edmund_Duke_Siege_Mode;
		unitTypes["Hero_Gerard_DuGalle"] = &UnitTypes::Hero_Gerard_DuGalle;
		unitTypes["Hero_Gui_Montag"] = &UnitTypes::Hero_Gui_Montag;
		unitTypes["Hero_Hyperion"] = &UnitTypes::Hero_Hyperion;
		unitTypes["Hero_Jim_Raynor_Marine"] = &UnitTypes::Hero_Jim_Raynor_Marine;
		unitTypes["Hero_Jim_Raynor_Vulture"] = &UnitTypes::Hero_Jim_Raynor_Vulture;
		unitTypes["Hero_Magellan"] = &UnitTypes::Hero_Magellan;
		unitTypes["Hero_Norad_II"] = &UnitTypes::Hero_Norad_II;
		unitTypes["Hero_Samir_Duran"] = &UnitTypes::Hero_Samir_Duran;
		unitTypes["Hero_Sarah_Kerrigan"] = &UnitTypes::Hero_Sarah_Kerrigan;
		unitTypes["Hero_Tom_Kazansky"] = &UnitTypes::Hero_Tom_Kazansky;
		unitTypes["Terran_Civilian"] = &UnitTypes::Terran_Civilian;
		unitTypes["Terran_Academy"] = &UnitTypes::Terran_Academy;
		unitTypes["Terran_Armory"] = &UnitTypes::Terran_Armory;
		unitTypes["Terran_Barracks"] = &UnitTypes::Terran_Barracks;
		unitTypes["Terran_Bunker"] = &UnitTypes::Terran_Bunker;
		unitTypes["Terran_Command_Center"] = &UnitTypes::Terran_Command_Center;
		unitTypes["Terran_Engineering_Bay"] = &UnitTypes::Terran_Engineering_Bay;
		unitTypes["Terran_Factory"] = &UnitTypes::Terran_Factory;
		unitTypes["Terran_Missile_Turret"] = &UnitTypes::Terran_Missile_Turret;
		unitTypes["Terran_Refinery"] = &UnitTypes::Terran_Refinery;
		unitTypes["Terran_Science_Facility"] = &UnitTypes::Terran_Science_Facility;
		unitTypes["Terran_Starport"] = &UnitTypes::Terran_Starport;
		unitTypes["Terran_Supply_Depot"] = &UnitTypes::Terran_Supply_Depot;
		unitTypes["Terran_Comsat_Station"] = &UnitTypes::Terran_Comsat_Station;
		unitTypes["Terran_Control_Tower"] = &UnitTypes::Terran_Control_Tower;
		unitTypes["Terran_Covert_Ops"] = &UnitTypes::Terran_Covert_Ops;
		unitTypes["Terran_Machine_Shop"] = &UnitTypes::Terran_Machine_Shop;
		unitTypes["Terran_Nuclear_Silo"] = &UnitTypes::Terran_Nuclear_Silo;
		unitTypes["Terran_Physics_Lab"] = &UnitTypes::Terran_Physics_Lab;
		unitTypes["Special_Crashed_Norad_II"] = &UnitTypes::Special_Crashed_Norad_II;
		unitTypes["Special_Ion_Cannon"] = &UnitTypes::Special_Ion_Cannon;
		unitTypes["Special_Power_Generator"] = &UnitTypes::Special_Power_Generator;
		unitTypes["Special_Psi_Disrupter"] = &UnitTypes::Special_Psi_Disrupter;
		unitTypes["Protoss_Archon"] = &UnitTypes::Protoss_Archon;
		unitTypes["Protoss_Dark_Archon"] = &UnitTypes::Protoss_Dark_Archon;
		unitTypes["Protoss_Dark_Templar"] = &UnitTypes::Protoss_Dark_Templar;
		unitTypes["Protoss_Dragoon"] = &UnitTypes::Protoss_Dragoon;
		unitTypes["Protoss_High_Templar"] = &UnitTypes::Protoss_High_Templar;
		unitTypes["Protoss_Probe"] = &UnitTypes::Protoss_Probe;
		unitTypes["Protoss_Reaver"] = &UnitTypes::Protoss_Reaver;
		unitTypes["Protoss_Scarab"] = &UnitTypes::Protoss_Scarab;
		unitTypes["Protoss_Zealot"] = &UnitTypes::Protoss_Zealot;
		unitTypes["Protoss_Arbiter"] = &UnitTypes::Protoss_Arbiter;
		unitTypes["Protoss_Carrier"] = &UnitTypes::Protoss_Carrier;
		unitTypes["Protoss_Corsair"] = &UnitTypes::Protoss_Corsair;
		unitTypes["Protoss_Interceptor"] = &UnitTypes::Protoss_Interceptor;
		unitTypes["Protoss_Observer"] = &UnitTypes::Protoss_Observer;
		unitTypes["Protoss_Scout"] = &UnitTypes::Protoss_Scout;
		unitTypes["Protoss_Shuttle"] = &UnitTypes::Protoss_Shuttle;
		unitTypes["Hero_Aldaris"] = &UnitTypes::Hero_Aldaris;
		unitTypes["Hero_Artanis"] = &UnitTypes::Hero_Artanis;
		unitTypes["Hero_Danimoth"] = &UnitTypes::Hero_Danimoth;
		unitTypes["Hero_Dark_Templar"] = &UnitTypes::Hero_Dark_Templar;
		unitTypes["Hero_Fenix_Dragoon"] = &UnitTypes::Hero_Fenix_Dragoon;
		unitTypes["Hero_Fenix_Zealot"] = &UnitTypes::Hero_Fenix_Zealot;
		unitTypes["Hero_Gantrithor"] = &UnitTypes::Hero_Gantrithor;
		unitTypes["Hero_Mojo"] = &UnitTypes::Hero_Mojo;
		unitTypes["Hero_Raszagal"] = &UnitTypes::Hero_Raszagal;
		unitTypes["Hero_Tassadar"] = &UnitTypes::Hero_Tassadar;
		unitTypes["Hero_Tassadar_Zeratul_Archon"] = &UnitTypes::Hero_Tassadar_Zeratul_Archon;
		unitTypes["Hero_Warbringer"] = &UnitTypes::Hero_Warbringer;
		unitTypes["Hero_Zeratul"] = &UnitTypes::Hero_Zeratul;
		unitTypes["Protoss_Arbiter_Tribunal"] = &UnitTypes::Protoss_Arbiter_Tribunal;
		unitTypes["Protoss_Assimilator"] = &UnitTypes::Protoss_Assimilator;
		unitTypes["Protoss_Citadel_of_Adun"] = &UnitTypes::Protoss_Citadel_of_Adun;
		unitTypes["Protoss_Cybernetics_Core"] = &UnitTypes::Protoss_Cybernetics_Core;
		unitTypes["Protoss_Fleet_Beacon"] = &UnitTypes::Protoss_Fleet_Beacon;
		unitTypes["Protoss_Forge"] = &UnitTypes::Protoss_Forge;
		unitTypes["Protoss_Gateway"] = &UnitTypes::Protoss_Gateway;
		unitTypes["Protoss_Nexus"] = &UnitTypes::Protoss_Nexus;
		unitTypes["Protoss_Observatory"] = &UnitTypes::Protoss_Observatory;
		unitTypes["Protoss_Photon_Cannon"] = &UnitTypes::Protoss_Photon_Cannon;
		unitTypes["Protoss_Pylon"] = &UnitTypes::Protoss_Pylon;
		unitTypes["Protoss_Robotics_Facility"] = &UnitTypes::Protoss_Robotics_Facility;
		unitTypes["Protoss_Robotics_Support_Bay"] = &UnitTypes::Protoss_Robotics_Support_Bay;
		unitTypes["Protoss_Shield_Battery"] = &UnitTypes::Protoss_Shield_Battery;
		unitTypes["Protoss_Stargate"] = &UnitTypes::Protoss_Stargate;
		unitTypes["Protoss_Templar_Archives"] = &UnitTypes::Protoss_Templar_Archives;
		unitTypes["Special_Khaydarin_Crystal_Form"] = &UnitTypes::Special_Khaydarin_Crystal_Form;
		unitTypes["Special_Protoss_Temple"] = &UnitTypes::Special_Protoss_Temple;
		unitTypes["Special_Stasis_Cell_Prison"] = &UnitTypes::Special_Stasis_Cell_Prison;
		unitTypes["Special_Warp_Gate"] = &UnitTypes::Special_Warp_Gate;
		unitTypes["Special_XelNaga_Temple"] = &UnitTypes::Special_XelNaga_Temple;
		unitTypes["Zerg_Broodling"] = &UnitTypes::Zerg_Broodling;
		unitTypes["Zerg_Defiler"] = &UnitTypes::Zerg_Defiler;
		unitTypes["Zerg_Drone"] = &UnitTypes::Zerg_Drone;
		unitTypes["Zerg_Egg"] = &UnitTypes::Zerg_Egg;
		unitTypes["Zerg_Hydralisk"] = &UnitTypes::Zerg_Hydralisk;
		unitTypes["Zerg_Infested_Terran"] = &UnitTypes::Zerg_Infested_Terran;
		unitTypes["Zerg_Larva"] = &UnitTypes::Zerg_Larva;
		unitTypes["Zerg_Lurker"] = &UnitTypes::Zerg_Lurker;
		unitTypes["Zerg_Lurker_Egg"] = &UnitTypes::Zerg_Lurker_Egg;
		unitTypes["Zerg_Ultralisk"] = &UnitTypes::Zerg_Ultralisk;
		unitTypes["Zerg_Zergling"] = &UnitTypes::Zerg_Zergling;
		unitTypes["Zerg_Cocoon"] = &UnitTypes::Zerg_Cocoon;
		unitTypes["Zerg_Devourer"] = &UnitTypes::Zerg_Devourer;
		unitTypes["Zerg_Guardian"] = &UnitTypes::Zerg_Guardian;
		unitTypes["Zerg_Mutalisk"] = &UnitTypes::Zerg_Mutalisk;
		unitTypes["Zerg_Overlord"] = &UnitTypes::Zerg_Overlord;
		unitTypes["Zerg_Queen"] = &UnitTypes::Zerg_Queen;
		unitTypes["Zerg_Scourge"] = &UnitTypes::Zerg_Scourge;
		unitTypes["Hero_Devouring_One"] = &UnitTypes::Hero_Devouring_One;
		unitTypes["Hero_Hunter_Killer"] = &UnitTypes::Hero_Hunter_Killer;
		unitTypes["Hero_Infested_Duran"] = &UnitTypes::Hero_Infested_Duran;
		unitTypes["Hero_Infested_Kerrigan"] = &UnitTypes::Hero_Infested_Kerrigan;
		unitTypes["Hero_Kukulza_Guardian"] = &UnitTypes::Hero_Kukulza_Guardian;
		unitTypes["Hero_Kukulza_Mutalisk"] = &UnitTypes::Hero_Kukulza_Mutalisk;
		unitTypes["Hero_Matriarch"] = &UnitTypes::Hero_Matriarch;
		unitTypes["Hero_Torrasque"] = &UnitTypes::Hero_Torrasque;
		unitTypes["Hero_Unclean_One"] = &UnitTypes::Hero_Unclean_One;
		unitTypes["Hero_Yggdrasill"] = &UnitTypes::Hero_Yggdrasill;
		unitTypes["Zerg_Creep_Colony"] = &UnitTypes::Zerg_Creep_Colony;
		unitTypes["Zerg_Defiler_Mound"] = &UnitTypes::Zerg_Defiler_Mound;
		unitTypes["Zerg_Evolution_Chamber"] = &UnitTypes::Zerg_Evolution_Chamber;
		unitTypes["Zerg_Extractor"] = &UnitTypes::Zerg_Extractor;
		unitTypes["Zerg_Greater_Spire"] = &UnitTypes::Zerg_Greater_Spire;
		unitTypes["Zerg_Hatchery"] = &UnitTypes::Zerg_Hatchery;
		unitTypes["Zerg_Hive"] = &UnitTypes::Zerg_Hive;
		unitTypes["Zerg_Hydralisk_Den"] = &UnitTypes::Zerg_Hydralisk_Den;
		unitTypes["Zerg_Infested_Command_Center"] = &UnitTypes::Zerg_Infested_Command_Center;
		unitTypes["Zerg_Lair"] = &UnitTypes::Zerg_Lair;
		unitTypes["Zerg_Nydus_Canal"] = &UnitTypes::Zerg_Nydus_Canal;
		unitTypes["Zerg_Queens_Nest"] = &UnitTypes::Zerg_Queens_Nest;
		unitTypes["Zerg_Spawning_Pool"] = &UnitTypes::Zerg_Spawning_Pool;
		unitTypes["Zerg_Spire"] = &UnitTypes::Zerg_Spire;
		unitTypes["Zerg_Spore_Colony"] = &UnitTypes::Zerg_Spore_Colony;
		unitTypes["Zerg_Sunken_Colony"] = &UnitTypes::Zerg_Sunken_Colony;
		unitTypes["Zerg_Ultralisk_Cavern"] = &UnitTypes::Zerg_Ultralisk_Cavern;
		unitTypes["Special_Cerebrate"] = &UnitTypes::Special_Cerebrate;
		unitTypes["Special_Cerebrate_Daggoth"] = &UnitTypes::Special_Cerebrate_Daggoth;
		unitTypes["Special_Mature_Chrysalis"] = &UnitTypes::Special_Mature_Chrysalis;
		unitTypes["Special_Overmind"] = &UnitTypes::Special_Overmind;
		unitTypes["Special_Overmind_Cocoon"] = &UnitTypes::Special_Overmind_Cocoon;
		unitTypes["Special_Overmind_With_Shell"] = &UnitTypes::Special_Overmind_With_Shell;
		unitTypes["Critter_Bengalaas"] = &UnitTypes::Critter_Bengalaas;
		unitTypes["Critter_Kakaru"] = &UnitTypes::Critter_Kakaru;
		unitTypes["Critter_Ragnasaur"] = &UnitTypes::Critter_Ragnasaur;
		unitTypes["Critter_Rhynadon"] = &UnitTypes::Critter_Rhynadon;
		unitTypes["Critter_Scantid"] = &UnitTypes::Critter_Scantid;
		unitTypes["Critter_Ursadon"] = &UnitTypes::Critter_Ursadon;
		unitTypes["Resource_Mineral_Field"] = &UnitTypes::Resource_Mineral_Field;
		unitTypes["Resource_Mineral_Field_Type_2"] = &UnitTypes::Resource_Mineral_Field_Type_2;
		unitTypes["Resource_Mineral_Field_Type_3"] = &UnitTypes::Resource_Mineral_Field_Type_3;
		unitTypes["Resource_Vespene_Geyser"] = &UnitTypes::Resource_Vespene_Geyser;
		unitTypes["Spell_Dark_Swarm"] = &UnitTypes::Spell_Dark_Swarm;
		unitTypes["Spell_Disruption_Web"] = &UnitTypes::Spell_Disruption_Web;
		unitTypes["Spell_Scanner_Sweep"] = &UnitTypes::Spell_Scanner_Sweep;
		unitTypes["Special_Protoss_Beacon"] = &UnitTypes::Special_Protoss_Beacon;
		unitTypes["Special_Protoss_Flag_Beacon"] = &UnitTypes::Special_Protoss_Flag_Beacon;
		unitTypes["Special_Terran_Beacon"] = &UnitTypes::Special_Terran_Beacon;
		unitTypes["Special_Terran_Flag_Beacon"] = &UnitTypes::Special_Terran_Flag_Beacon;
		unitTypes["Special_Zerg_Beacon"] = &UnitTypes::Special_Zerg_Beacon;
		unitTypes["Special_Zerg_Flag_Beacon"] = &UnitTypes::Special_Zerg_Flag_Beacon;
		unitTypes["Powerup_Data_Disk"] = &UnitTypes::Powerup_Data_Disk;
		unitTypes["Powerup_Flag"] = &UnitTypes::Powerup_Flag;
		unitTypes["Powerup_Khalis_Crystal"] = &UnitTypes::Powerup_Khalis_Crystal;
		unitTypes["Powerup_Khaydarin_Crystal"] = &UnitTypes::Powerup_Khaydarin_Crystal;
		unitTypes["Powerup_Mineral_Cluster_Type_1"] = &UnitTypes::Powerup_Mineral_Cluster_Type_1;
		unitTypes["Powerup_Mineral_Cluster_Type_2"] = &UnitTypes::Powerup_Mineral_Cluster_Type_2;
		unitTypes["Powerup_Protoss_Gas_Orb_Type_1"] = &UnitTypes::Powerup_Protoss_Gas_Orb_Type_1;
		unitTypes["Powerup_Protoss_Gas_Orb_Type_2"] = &UnitTypes::Powerup_Protoss_Gas_Orb_Type_2;
		unitTypes["Powerup_Psi_Emitter"] = &UnitTypes::Powerup_Psi_Emitter;
		unitTypes["Powerup_Terran_Gas_Tank_Type_1"] = &UnitTypes::Powerup_Terran_Gas_Tank_Type_1;
		unitTypes["Powerup_Terran_Gas_Tank_Type_2"] = &UnitTypes::Powerup_Terran_Gas_Tank_Type_2;
		unitTypes["Powerup_Uraj_Crystal"] = &UnitTypes::Powerup_Uraj_Crystal;
		unitTypes["Powerup_Young_Chrysalis"] = &UnitTypes::Powerup_Young_Chrysalis;
		unitTypes["Powerup_Zerg_Gas_Sac_Type_1"] = &UnitTypes::Powerup_Zerg_Gas_Sac_Type_1;
		unitTypes["Powerup_Zerg_Gas_Sac_Type_2"] = &UnitTypes::Powerup_Zerg_Gas_Sac_Type_2;
		unitTypes["Special_Floor_Gun_Trap"] = &UnitTypes::Special_Floor_Gun_Trap;
		unitTypes["Special_Floor_Missile_Trap"] = &UnitTypes::Special_Floor_Missile_Trap;
		unitTypes["Special_Right_Wall_Flame_Trap"] = &UnitTypes::Special_Right_Wall_Flame_Trap;
		unitTypes["Special_Right_Wall_Missile_Trap"] = &UnitTypes::Special_Right_Wall_Missile_Trap;
		unitTypes["Special_Wall_Flame_Trap"] = &UnitTypes::Special_Wall_Flame_Trap;
		unitTypes["Special_Wall_Missile_Trap"] = &UnitTypes::Special_Wall_Missile_Trap;
		unitTypes["Special_Pit_Door"] = &UnitTypes::Special_Pit_Door;
		unitTypes["Special_Right_Pit_Door"] = &UnitTypes::Special_Right_Pit_Door;
		unitTypes["Special_Right_Upper_Level_Door"] = &UnitTypes::Special_Right_Upper_Level_Door;
		unitTypes["Special_Upper_Level_Door"] = &UnitTypes::Special_Upper_Level_Door;
		unitTypes["Special_Cargo_Ship"] = &UnitTypes::Special_Cargo_Ship;
		unitTypes["Special_Floor_Hatch"] = &UnitTypes::Special_Floor_Hatch;
		unitTypes["Special_Independant_Starport"] = &UnitTypes::Special_Independant_Starport;
		unitTypes["Special_Map_Revealer"] = &UnitTypes::Special_Map_Revealer;
		unitTypes["Special_Mercenary_Gunship"] = &UnitTypes::Special_Mercenary_Gunship;
		unitTypes["Special_Start_Location"] = &UnitTypes::Special_Start_Location;

		unitTypes["None"] = &UnitTypes::None;
		unitTypes["AllUnits"] = &UnitTypes::AllUnits;
		unitTypes["Men"] = &UnitTypes::Men;
		unitTypes["Buildings"] = &UnitTypes::Buildings;
		unitTypes["Factories"] = &UnitTypes::Factories;
		unitTypes["Unknown"] = &UnitTypes::Unknown;

		auto unitTypesEnum = unitTypes.create_named("Enum");
		unitTypesEnum["Terran_Marine"] = UnitTypes::Enum::Terran_Marine;
		unitTypesEnum["Terran_Ghost"] = UnitTypes::Enum::Terran_Ghost;
		unitTypesEnum["Terran_Vulture"] = UnitTypes::Enum::Terran_Vulture;
		unitTypesEnum["Terran_Goliath"] = UnitTypes::Enum::Terran_Goliath;
		unitTypesEnum["Terran_Goliath_Turret"] = UnitTypes::Enum::Terran_Goliath_Turret;
		unitTypesEnum["Terran_Siege_Tank_Tank_Mode"] = UnitTypes::Enum::Terran_Siege_Tank_Tank_Mode;
		unitTypesEnum["Terran_Siege_Tank_Tank_Mode_Turret"] = UnitTypes::Enum::Terran_Siege_Tank_Tank_Mode_Turret;
		unitTypesEnum["Terran_SCV"] = UnitTypes::Enum::Terran_SCV;
		unitTypesEnum["Terran_Wraith"] = UnitTypes::Enum::Terran_Wraith;
		unitTypesEnum["Terran_Science_Vessel"] = UnitTypes::Enum::Terran_Science_Vessel;
		unitTypesEnum["Hero_Gui_Montag"] = UnitTypes::Enum::Hero_Gui_Montag;
		unitTypesEnum["Terran_Dropship"] = UnitTypes::Enum::Terran_Dropship;
		unitTypesEnum["Terran_Battlecruiser"] = UnitTypes::Enum::Terran_Battlecruiser;
		unitTypesEnum["Terran_Vulture_Spider_Mine"] = UnitTypes::Enum::Terran_Vulture_Spider_Mine;
		unitTypesEnum["Terran_Nuclear_Missile"] = UnitTypes::Enum::Terran_Nuclear_Missile;
		unitTypesEnum["Terran_Civilian"] = UnitTypes::Enum::Terran_Civilian;
		unitTypesEnum["Hero_Sarah_Kerrigan"] = UnitTypes::Enum::Hero_Sarah_Kerrigan;
		unitTypesEnum["Hero_Alan_Schezar"] = UnitTypes::Enum::Hero_Alan_Schezar;
		unitTypesEnum["Hero_Alan_Schezar_Turret"] = UnitTypes::Enum::Hero_Alan_Schezar_Turret;
		unitTypesEnum["Hero_Jim_Raynor_Vulture"] = UnitTypes::Enum::Hero_Jim_Raynor_Vulture;
		unitTypesEnum["Hero_Jim_Raynor_Marine"] = UnitTypes::Enum::Hero_Jim_Raynor_Marine;
		unitTypesEnum["Hero_Tom_Kazansky"] = UnitTypes::Enum::Hero_Tom_Kazansky;
		unitTypesEnum["Hero_Magellan"] = UnitTypes::Enum::Hero_Magellan;
		unitTypesEnum["Hero_Edmund_Duke_Tank_Mode"] = UnitTypes::Enum::Hero_Edmund_Duke_Tank_Mode;
		unitTypesEnum["Hero_Edmund_Duke_Tank_Mode_Turret"] = UnitTypes::Enum::Hero_Edmund_Duke_Tank_Mode_Turret;
		unitTypesEnum["Hero_Edmund_Duke_Siege_Mode"] = UnitTypes::Enum::Hero_Edmund_Duke_Siege_Mode;
		unitTypesEnum["Hero_Edmund_Duke_Siege_Mode_Turret"] = UnitTypes::Enum::Hero_Edmund_Duke_Siege_Mode_Turret;
		unitTypesEnum["Hero_Arcturus_Mengsk"] = UnitTypes::Enum::Hero_Arcturus_Mengsk;
		unitTypesEnum["Hero_Hyperion"] = UnitTypes::Enum::Hero_Hyperion;
		unitTypesEnum["Hero_Norad_II"] = UnitTypes::Enum::Hero_Norad_II;
		unitTypesEnum["Terran_Siege_Tank_Siege_Mode"] = UnitTypes::Enum::Terran_Siege_Tank_Siege_Mode;
		unitTypesEnum["Terran_Siege_Tank_Siege_Mode_Turret"] = UnitTypes::Enum::Terran_Siege_Tank_Siege_Mode_Turret;
		unitTypesEnum["Terran_Firebat"] = UnitTypes::Enum::Terran_Firebat;
		unitTypesEnum["Spell_Scanner_Sweep"] = UnitTypes::Enum::Spell_Scanner_Sweep;
		unitTypesEnum["Terran_Medic"] = UnitTypes::Enum::Terran_Medic;
		unitTypesEnum["Zerg_Larva"] = UnitTypes::Enum::Zerg_Larva;
		unitTypesEnum["Zerg_Egg"] = UnitTypes::Enum::Zerg_Egg;
		unitTypesEnum["Zerg_Zergling"] = UnitTypes::Enum::Zerg_Zergling;
		unitTypesEnum["Zerg_Hydralisk"] = UnitTypes::Enum::Zerg_Hydralisk;
		unitTypesEnum["Zerg_Ultralisk"] = UnitTypes::Enum::Zerg_Ultralisk;
		unitTypesEnum["Zerg_Broodling"] = UnitTypes::Enum::Zerg_Broodling;
		unitTypesEnum["Zerg_Drone"] = UnitTypes::Enum::Zerg_Drone;
		unitTypesEnum["Zerg_Overlord"] = UnitTypes::Enum::Zerg_Overlord;
		unitTypesEnum["Zerg_Mutalisk"] = UnitTypes::Enum::Zerg_Mutalisk;
		unitTypesEnum["Zerg_Guardian"] = UnitTypes::Enum::Zerg_Guardian;
		unitTypesEnum["Zerg_Queen"] = UnitTypes::Enum::Zerg_Queen;
		unitTypesEnum["Zerg_Defiler"] = UnitTypes::Enum::Zerg_Defiler;
		unitTypesEnum["Zerg_Scourge"] = UnitTypes::Enum::Zerg_Scourge;
		unitTypesEnum["Hero_Torrasque"] = UnitTypes::Enum::Hero_Torrasque;
		unitTypesEnum["Hero_Matriarch"] = UnitTypes::Enum::Hero_Matriarch;
		unitTypesEnum["Zerg_Infested_Terran"] = UnitTypes::Enum::Zerg_Infested_Terran;
		unitTypesEnum["Hero_Infested_Kerrigan"] = UnitTypes::Enum::Hero_Infested_Kerrigan;
		unitTypesEnum["Hero_Unclean_One"] = UnitTypes::Enum::Hero_Unclean_One;
		unitTypesEnum["Hero_Hunter_Killer"] = UnitTypes::Enum::Hero_Hunter_Killer;
		unitTypesEnum["Hero_Devouring_One"] = UnitTypes::Enum::Hero_Devouring_One;
		unitTypesEnum["Hero_Kukulza_Mutalisk"] = UnitTypes::Enum::Hero_Kukulza_Mutalisk;
		unitTypesEnum["Hero_Kukulza_Guardian"] = UnitTypes::Enum::Hero_Kukulza_Guardian;
		unitTypesEnum["Hero_Yggdrasill"] = UnitTypes::Enum::Hero_Yggdrasill;
		unitTypesEnum["Terran_Valkyrie"] = UnitTypes::Enum::Terran_Valkyrie;
		unitTypesEnum["Zerg_Cocoon"] = UnitTypes::Enum::Zerg_Cocoon;
		unitTypesEnum["Protoss_Corsair"] = UnitTypes::Enum::Protoss_Corsair;
		unitTypesEnum["Protoss_Dark_Templar"] = UnitTypes::Enum::Protoss_Dark_Templar;
		unitTypesEnum["Zerg_Devourer"] = UnitTypes::Enum::Zerg_Devourer;
		unitTypesEnum["Protoss_Dark_Archon"] = UnitTypes::Enum::Protoss_Dark_Archon;
		unitTypesEnum["Protoss_Probe"] = UnitTypes::Enum::Protoss_Probe;
		unitTypesEnum["Protoss_Zealot"] = UnitTypes::Enum::Protoss_Zealot;
		unitTypesEnum["Protoss_Dragoon"] = UnitTypes::Enum::Protoss_Dragoon;
		unitTypesEnum["Protoss_High_Templar"] = UnitTypes::Enum::Protoss_High_Templar;
		unitTypesEnum["Protoss_Archon"] = UnitTypes::Enum::Protoss_Archon;
		unitTypesEnum["Protoss_Shuttle"] = UnitTypes::Enum::Protoss_Shuttle;
		unitTypesEnum["Protoss_Scout"] = UnitTypes::Enum::Protoss_Scout;
		unitTypesEnum["Protoss_Arbiter"] = UnitTypes::Enum::Protoss_Arbiter;
		unitTypesEnum["Protoss_Carrier"] = UnitTypes::Enum::Protoss_Carrier;
		unitTypesEnum["Protoss_Interceptor"] = UnitTypes::Enum::Protoss_Interceptor;
		unitTypesEnum["Hero_Dark_Templar"] = UnitTypes::Enum::Hero_Dark_Templar;
		unitTypesEnum["Hero_Zeratul"] = UnitTypes::Enum::Hero_Zeratul;
		unitTypesEnum["Hero_Tassadar_Zeratul_Archon"] = UnitTypes::Enum::Hero_Tassadar_Zeratul_Archon;
		unitTypesEnum["Hero_Fenix_Zealot"] = UnitTypes::Enum::Hero_Fenix_Zealot;
		unitTypesEnum["Hero_Fenix_Dragoon"] = UnitTypes::Enum::Hero_Fenix_Dragoon;
		unitTypesEnum["Hero_Tassadar"] = UnitTypes::Enum::Hero_Tassadar;
		unitTypesEnum["Hero_Mojo"] = UnitTypes::Enum::Hero_Mojo;
		unitTypesEnum["Hero_Warbringer"] = UnitTypes::Enum::Hero_Warbringer;
		unitTypesEnum["Hero_Gantrithor"] = UnitTypes::Enum::Hero_Gantrithor;
		unitTypesEnum["Protoss_Reaver"] = UnitTypes::Enum::Protoss_Reaver;
		unitTypesEnum["Protoss_Observer"] = UnitTypes::Enum::Protoss_Observer;
		unitTypesEnum["Protoss_Scarab"] = UnitTypes::Enum::Protoss_Scarab;
		unitTypesEnum["Hero_Danimoth"] = UnitTypes::Enum::Hero_Danimoth;
		unitTypesEnum["Hero_Aldaris"] = UnitTypes::Enum::Hero_Aldaris;
		unitTypesEnum["Hero_Artanis"] = UnitTypes::Enum::Hero_Artanis;
		unitTypesEnum["Critter_Rhynadon"] = UnitTypes::Enum::Critter_Rhynadon;
		unitTypesEnum["Critter_Bengalaas"] = UnitTypes::Enum::Critter_Bengalaas;
		unitTypesEnum["Special_Cargo_Ship"] = UnitTypes::Enum::Special_Cargo_Ship;
		unitTypesEnum["Special_Mercenary_Gunship"] = UnitTypes::Enum::Special_Mercenary_Gunship;
		unitTypesEnum["Critter_Scantid"] = UnitTypes::Enum::Critter_Scantid;
		unitTypesEnum["Critter_Kakaru"] = UnitTypes::Enum::Critter_Kakaru;
		unitTypesEnum["Critter_Ragnasaur"] = UnitTypes::Enum::Critter_Ragnasaur;
		unitTypesEnum["Critter_Ursadon"] = UnitTypes::Enum::Critter_Ursadon;
		unitTypesEnum["Zerg_Lurker_Egg"] = UnitTypes::Enum::Zerg_Lurker_Egg;
		unitTypesEnum["Hero_Raszagal"] = UnitTypes::Enum::Hero_Raszagal;
		unitTypesEnum["Hero_Samir_Duran"] = UnitTypes::Enum::Hero_Samir_Duran;
		unitTypesEnum["Hero_Alexei_Stukov"] = UnitTypes::Enum::Hero_Alexei_Stukov;
		unitTypesEnum["Special_Map_Revealer"] = UnitTypes::Enum::Special_Map_Revealer;
		unitTypesEnum["Hero_Gerard_DuGalle"] = UnitTypes::Enum::Hero_Gerard_DuGalle;
		unitTypesEnum["Zerg_Lurker"] = UnitTypes::Enum::Zerg_Lurker;
		unitTypesEnum["Hero_Infested_Duran"] = UnitTypes::Enum::Hero_Infested_Duran;
		unitTypesEnum["Spell_Disruption_Web"] = UnitTypes::Enum::Spell_Disruption_Web;
		unitTypesEnum["Terran_Command_Center"] = UnitTypes::Enum::Terran_Command_Center;
		unitTypesEnum["Terran_Comsat_Station"] = UnitTypes::Enum::Terran_Comsat_Station;
		unitTypesEnum["Terran_Nuclear_Silo"] = UnitTypes::Enum::Terran_Nuclear_Silo;
		unitTypesEnum["Terran_Supply_Depot"] = UnitTypes::Enum::Terran_Supply_Depot;
		unitTypesEnum["Terran_Refinery"] = UnitTypes::Enum::Terran_Refinery;
		unitTypesEnum["Terran_Barracks"] = UnitTypes::Enum::Terran_Barracks;
		unitTypesEnum["Terran_Academy"] = UnitTypes::Enum::Terran_Academy;
		unitTypesEnum["Terran_Factory"] = UnitTypes::Enum::Terran_Factory;
		unitTypesEnum["Terran_Starport"] = UnitTypes::Enum::Terran_Starport;
		unitTypesEnum["Terran_Control_Tower"] = UnitTypes::Enum::Terran_Control_Tower;
		unitTypesEnum["Terran_Science_Facility"] = UnitTypes::Enum::Terran_Science_Facility;
		unitTypesEnum["Terran_Covert_Ops"] = UnitTypes::Enum::Terran_Covert_Ops;
		unitTypesEnum["Terran_Physics_Lab"] = UnitTypes::Enum::Terran_Physics_Lab;
		unitTypesEnum["Unused_Terran1"] = UnitTypes::Enum::Unused_Terran1;
		unitTypesEnum["Terran_Machine_Shop"] = UnitTypes::Enum::Terran_Machine_Shop;
		unitTypesEnum["Unused_Terran2"] = UnitTypes::Enum::Unused_Terran2;
		unitTypesEnum["Terran_Engineering_Bay"] = UnitTypes::Enum::Terran_Engineering_Bay;
		unitTypesEnum["Terran_Armory"] = UnitTypes::Enum::Terran_Armory;
		unitTypesEnum["Terran_Missile_Turret"] = UnitTypes::Enum::Terran_Missile_Turret;
		unitTypesEnum["Terran_Bunker"] = UnitTypes::Enum::Terran_Bunker;
		unitTypesEnum["Special_Crashed_Norad_II"] = UnitTypes::Enum::Special_Crashed_Norad_II;
		unitTypesEnum["Special_Ion_Cannon"] = UnitTypes::Enum::Special_Ion_Cannon;
		unitTypesEnum["Powerup_Uraj_Crystal"] = UnitTypes::Enum::Powerup_Uraj_Crystal;
		unitTypesEnum["Powerup_Khalis_Crystal"] = UnitTypes::Enum::Powerup_Khalis_Crystal;
		unitTypesEnum["Zerg_Infested_Command_Center"] = UnitTypes::Enum::Zerg_Infested_Command_Center;
		unitTypesEnum["Zerg_Hatchery"] = UnitTypes::Enum::Zerg_Hatchery;
		unitTypesEnum["Zerg_Lair"] = UnitTypes::Enum::Zerg_Lair;
		unitTypesEnum["Zerg_Hive"] = UnitTypes::Enum::Zerg_Hive;
		unitTypesEnum["Zerg_Nydus_Canal"] = UnitTypes::Enum::Zerg_Nydus_Canal;
		unitTypesEnum["Zerg_Hydralisk_Den"] = UnitTypes::Enum::Zerg_Hydralisk_Den;
		unitTypesEnum["Zerg_Defiler_Mound"] = UnitTypes::Enum::Zerg_Defiler_Mound;
		unitTypesEnum["Zerg_Greater_Spire"] = UnitTypes::Enum::Zerg_Greater_Spire;
		unitTypesEnum["Zerg_Queens_Nest"] = UnitTypes::Enum::Zerg_Queens_Nest;
		unitTypesEnum["Zerg_Evolution_Chamber"] = UnitTypes::Enum::Zerg_Evolution_Chamber;
		unitTypesEnum["Zerg_Ultralisk_Cavern"] = UnitTypes::Enum::Zerg_Ultralisk_Cavern;
		unitTypesEnum["Zerg_Spire"] = UnitTypes::Enum::Zerg_Spire;
		unitTypesEnum["Zerg_Spawning_Pool"] = UnitTypes::Enum::Zerg_Spawning_Pool;
		unitTypesEnum["Zerg_Creep_Colony"] = UnitTypes::Enum::Zerg_Creep_Colony;
		unitTypesEnum["Zerg_Spore_Colony"] = UnitTypes::Enum::Zerg_Spore_Colony;
		unitTypesEnum["Unused_Zerg1"] = UnitTypes::Enum::Unused_Zerg1;
		unitTypesEnum["Zerg_Sunken_Colony"] = UnitTypes::Enum::Zerg_Sunken_Colony;
		unitTypesEnum["Special_Overmind_With_Shell"] = UnitTypes::Enum::Special_Overmind_With_Shell;
		unitTypesEnum["Special_Overmind"] = UnitTypes::Enum::Special_Overmind;
		unitTypesEnum["Zerg_Extractor"] = UnitTypes::Enum::Zerg_Extractor;
		unitTypesEnum["Special_Mature_Chrysalis"] = UnitTypes::Enum::Special_Mature_Chrysalis;
		unitTypesEnum["Special_Cerebrate"] = UnitTypes::Enum::Special_Cerebrate;
		unitTypesEnum["Special_Cerebrate_Daggoth"] = UnitTypes::Enum::Special_Cerebrate_Daggoth;
		unitTypesEnum["Unused_Zerg2"] = UnitTypes::Enum::Unused_Zerg2;
		unitTypesEnum["Protoss_Nexus"] = UnitTypes::Enum::Protoss_Nexus;
		unitTypesEnum["Protoss_Robotics_Facility"] = UnitTypes::Enum::Protoss_Robotics_Facility;
		unitTypesEnum["Protoss_Pylon"] = UnitTypes::Enum::Protoss_Pylon;
		unitTypesEnum["Protoss_Assimilator"] = UnitTypes::Enum::Protoss_Assimilator;
		unitTypesEnum["Unused_Protoss1"] = UnitTypes::Enum::Unused_Protoss1;
		unitTypesEnum["Protoss_Observatory"] = UnitTypes::Enum::Protoss_Observatory;
		unitTypesEnum["Protoss_Gateway"] = UnitTypes::Enum::Protoss_Gateway;
		unitTypesEnum["Unused_Protoss2"] = UnitTypes::Enum::Unused_Protoss2;
		unitTypesEnum["Protoss_Photon_Cannon"] = UnitTypes::Enum::Protoss_Photon_Cannon;
		unitTypesEnum["Protoss_Citadel_of_Adun"] = UnitTypes::Enum::Protoss_Citadel_of_Adun;
		unitTypesEnum["Protoss_Cybernetics_Core"] = UnitTypes::Enum::Protoss_Cybernetics_Core;
		unitTypesEnum["Protoss_Templar_Archives"] = UnitTypes::Enum::Protoss_Templar_Archives;
		unitTypesEnum["Protoss_Forge"] = UnitTypes::Enum::Protoss_Forge;
		unitTypesEnum["Protoss_Stargate"] = UnitTypes::Enum::Protoss_Stargate;
		unitTypesEnum["Special_Stasis_Cell_Prison"] = UnitTypes::Enum::Special_Stasis_Cell_Prison;
		unitTypesEnum["Protoss_Fleet_Beacon"] = UnitTypes::Enum::Protoss_Fleet_Beacon;
		unitTypesEnum["Protoss_Arbiter_Tribunal"] = UnitTypes::Enum::Protoss_Arbiter_Tribunal;
		unitTypesEnum["Protoss_Robotics_Support_Bay"] = UnitTypes::Enum::Protoss_Robotics_Support_Bay;
		unitTypesEnum["Protoss_Shield_Battery"] = UnitTypes::Enum::Protoss_Shield_Battery;
		unitTypesEnum["Special_Khaydarin_Crystal_Form"] = UnitTypes::Enum::Special_Khaydarin_Crystal_Form;
		unitTypesEnum["Special_Protoss_Temple"] = UnitTypes::Enum::Special_Protoss_Temple;
		unitTypesEnum["Special_XelNaga_Temple"] = UnitTypes::Enum::Special_XelNaga_Temple;
		unitTypesEnum["Resource_Mineral_Field"] = UnitTypes::Enum::Resource_Mineral_Field;
		unitTypesEnum["Resource_Mineral_Field_Type_2"] = UnitTypes::Enum::Resource_Mineral_Field_Type_2;
		unitTypesEnum["Resource_Mineral_Field_Type_3"] = UnitTypes::Enum::Resource_Mineral_Field_Type_3;
		unitTypesEnum["Unused_Cave"] = UnitTypes::Enum::Unused_Cave;
		unitTypesEnum["Unused_Cave_In"] = UnitTypes::Enum::Unused_Cave_In;
		unitTypesEnum["Unused_Cantina"] = UnitTypes::Enum::Unused_Cantina;
		unitTypesEnum["Unused_Mining_Platform"] = UnitTypes::Enum::Unused_Mining_Platform;
		unitTypesEnum["Unused_Independant_Command_Center"] = UnitTypes::Enum::Unused_Independant_Command_Center;
		unitTypesEnum["Special_Independant_Starport"] = UnitTypes::Enum::Special_Independant_Starport;
		unitTypesEnum["Unused_Independant_Jump_Gate"] = UnitTypes::Enum::Unused_Independant_Jump_Gate;
		unitTypesEnum["Unused_Ruins"] = UnitTypes::Enum::Unused_Ruins;
		unitTypesEnum["Unused_Khaydarin_Crystal_Formation"] = UnitTypes::Enum::Unused_Khaydarin_Crystal_Formation;
		unitTypesEnum["Resource_Vespene_Geyser"] = UnitTypes::Enum::Resource_Vespene_Geyser;
		unitTypesEnum["Special_Warp_Gate"] = UnitTypes::Enum::Special_Warp_Gate;
		unitTypesEnum["Special_Psi_Disrupter"] = UnitTypes::Enum::Special_Psi_Disrupter;
		unitTypesEnum["Unused_Zerg_Marker"] = UnitTypes::Enum::Unused_Zerg_Marker;
		unitTypesEnum["Unused_Terran_Marker"] = UnitTypes::Enum::Unused_Terran_Marker;
		unitTypesEnum["Unused_Protoss_Marker"] = UnitTypes::Enum::Unused_Protoss_Marker;
		unitTypesEnum["Special_Zerg_Beacon"] = UnitTypes::Enum::Special_Zerg_Beacon;
		unitTypesEnum["Special_Terran_Beacon"] = UnitTypes::Enum::Special_Terran_Beacon;
		unitTypesEnum["Special_Protoss_Beacon"] = UnitTypes::Enum::Special_Protoss_Beacon;
		unitTypesEnum["Special_Zerg_Flag_Beacon"] = UnitTypes::Enum::Special_Zerg_Flag_Beacon;
		unitTypesEnum["Special_Terran_Flag_Beacon"] = UnitTypes::Enum::Special_Terran_Flag_Beacon;
		unitTypesEnum["Special_Protoss_Flag_Beacon"] = UnitTypes::Enum::Special_Protoss_Flag_Beacon;
		unitTypesEnum["Special_Power_Generator"] = UnitTypes::Enum::Special_Power_Generator;
		unitTypesEnum["Special_Overmind_Cocoon"] = UnitTypes::Enum::Special_Overmind_Cocoon;
		unitTypesEnum["Spell_Dark_Swarm"] = UnitTypes::Enum::Spell_Dark_Swarm;
		unitTypesEnum["Special_Floor_Missile_Trap"] = UnitTypes::Enum::Special_Floor_Missile_Trap;
		unitTypesEnum["Special_Floor_Hatch"] = UnitTypes::Enum::Special_Floor_Hatch;
		unitTypesEnum["Special_Upper_Level_Door"] = UnitTypes::Enum::Special_Upper_Level_Door;
		unitTypesEnum["Special_Right_Upper_Level_Door"] = UnitTypes::Enum::Special_Right_Upper_Level_Door;
		unitTypesEnum["Special_Pit_Door"] = UnitTypes::Enum::Special_Pit_Door;
		unitTypesEnum["Special_Right_Pit_Door"] = UnitTypes::Enum::Special_Right_Pit_Door;
		unitTypesEnum["Special_Floor_Gun_Trap"] = UnitTypes::Enum::Special_Floor_Gun_Trap;
		unitTypesEnum["Special_Wall_Missile_Trap"] = UnitTypes::Enum::Special_Wall_Missile_Trap;
		unitTypesEnum["Special_Wall_Flame_Trap"] = UnitTypes::Enum::Special_Wall_Flame_Trap;
		unitTypesEnum["Special_Right_Wall_Missile_Trap"] = UnitTypes::Enum::Special_Right_Wall_Missile_Trap;
		unitTypesEnum["Special_Right_Wall_Flame_Trap"] = UnitTypes::Enum::Special_Right_Wall_Flame_Trap;
		unitTypesEnum["Special_Start_Location"] = UnitTypes::Enum::Special_Start_Location;
		unitTypesEnum["Powerup_Flag"] = UnitTypes::Enum::Powerup_Flag;
		unitTypesEnum["Powerup_Young_Chrysalis"] = UnitTypes::Enum::Powerup_Young_Chrysalis;
		unitTypesEnum["Powerup_Psi_Emitter"] = UnitTypes::Enum::Powerup_Psi_Emitter;
		unitTypesEnum["Powerup_Data_Disk"] = UnitTypes::Enum::Powerup_Data_Disk;
		unitTypesEnum["Powerup_Khaydarin_Crystal"] = UnitTypes::Enum::Powerup_Khaydarin_Crystal;
		unitTypesEnum["Powerup_Mineral_Cluster_Type_1"] = UnitTypes::Enum::Powerup_Mineral_Cluster_Type_1;
		unitTypesEnum["Powerup_Mineral_Cluster_Type_2"] = UnitTypes::Enum::Powerup_Mineral_Cluster_Type_2;
		unitTypesEnum["Powerup_Protoss_Gas_Orb_Type_1"] = UnitTypes::Enum::Powerup_Protoss_Gas_Orb_Type_1;
		unitTypesEnum["Powerup_Protoss_Gas_Orb_Type_2"] = UnitTypes::Enum::Powerup_Protoss_Gas_Orb_Type_2;
		unitTypesEnum["Powerup_Zerg_Gas_Sac_Type_1"] = UnitTypes::Enum::Powerup_Zerg_Gas_Sac_Type_1;
		unitTypesEnum["Powerup_Zerg_Gas_Sac_Type_2"] = UnitTypes::Enum::Powerup_Zerg_Gas_Sac_Type_2;
		unitTypesEnum["Powerup_Terran_Gas_Tank_Type_1"] = UnitTypes::Enum::Powerup_Terran_Gas_Tank_Type_1;
		unitTypesEnum["Powerup_Terran_Gas_Tank_Type_2"] = UnitTypes::Enum::Powerup_Terran_Gas_Tank_Type_2;

		unitTypesEnum["None"] = UnitTypes::Enum::None;
		unitTypesEnum["AllUnits"] = UnitTypes::Enum::AllUnits;
		unitTypesEnum["Men"] = UnitTypes::Enum::Men;
		unitTypesEnum["Buildings"] = UnitTypes::Enum::Buildings;
		unitTypesEnum["Factories"] = UnitTypes::Enum::Factories;
		unitTypesEnum["Unknown"] = UnitTypes::Enum::Unknown;
		unitTypesEnum["MAX"] = UnitTypes::Enum::MAX;
	}
}